### ISSUE TITLE
Features, Compile time emit code, with filters for tennants

### ISSUE THREAD

**Issue by fasteddys** [Magicalizer/Magicalizer#1]
Hello, I love this, its really a scaffolding tool better than MS own tool. This makes so much sense.

One more thing is if we can author the rest end points first

Can we get filters & audit to be scaffolded as well, so we can have claims/permission and tenants
A simple picture of the components generated would help.
I would like to help make this a UI tool, where should I start
Can we also give users UI Views choice like BS 5 scaffolded
Can we make these modules Microservices compatible, so that they can be registered as dependencies in the master nodes.

wanted to share some additional resources to help in tooling.

- [ ]  https://github.com/KorzhCom/EasyData/tree/features/continuous-chunks / https://github.com/KorzhCom/EasyData  `DATA GRID`
- [ ] https://github.com/EasyAbp/Abp.EntityUi    ` UI to scaffold`
- [ ] https://github.com/damienbod/AspNetCoreMvcDynamicViews
- [ ] https://github.com/mo-esmp/DynamicRoleBasedAuthorizationNETCore   `Dynamic Auth Perms Auth`
- [ ] https://github.com/colinin/abp-next-admin  s`ample admin app`

UI stuff

- [ ] UI Builder https://github.com/BuilderIO/figma-html
- [ ] https://github.com/givanz/VvvebJs 
- [ ] https://github.com/topics/website-builder
- [ ] https://github.com/Kooboo/Kooboo

**Comment by DmitrySikorsky** [comment]
Thank you for feedback. In the current project I've found very interesting solution for tenants. It is based on configuring different DB contexts for the different tenants. I've tested it for 5000 tenants and there is no memory or CPU issues, everything works just perfect. I will thing if it should be added directly in Magicalizer, but it is easy to add manually.

What about UI. I don't think Magicalizer should contain anything related to UI. But you can look at for example https://github.com/platformus which is based on Magicalizer and has a lot of things to simply build UI (but manually). I was thinking to create Visual Studio extension or separate app to create admin sections automatically because it is required in every project we do, but have no time for that so far.

**Comment by fasteddys** [comment]
Hello @DmitrySikorsky , I think your project is one of the best fit for developers coming from a wordpress like background - which is a huge advantage, many of the concepts make sense, the others are very complicated and steep learning curve.

Documentation would be helpful, but the others are suggestions so that, they could incorporated at a plugin level, hence my recommendation. I can see the merit of your recommendation as well if we can get some better understanding on how to build components and plugins into platformus, with inplace update support for your new releases.

And, also a template with comments on how to hook in new entities or view models. And, thats where I was showing you some tools. I am happy to help build the generator tool for platformus if you can explain to the developer community the hooks, actions, lifecycle and also a visual arichitecture for modules or plugins to incorporate our own features.

**Comment by DmitrySikorsky** [comment]
Currently I'm working on the Platformus documentation (and project itself). I also want to improve Magicalizer's docs, but have to do everything step by step. I will provide examples for sure but can't promise that it will be done very fast.

**Comment by fasteddys** [comment]
BTW, check out 
https://github.com/jdanylko/Tuxboard for turnkey user driven dashboards 
also Check out raytha a new cms, and webvellaerp
